import { library } from '@fortawesome/fontawesome-svg-core'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'
import {
  faScissors,
  faStar,
  faStarHalfStroke,
  faLocationDot,
  faClock,
  faPhone,
  faEnvelope,
  faCalendarCheck,
  faArrowRight,
  faArrowLeft,
  faChevronDown,
  faBars,
  faTableCellsLarge,
  faXmark,
  faSun,
  faMoon,
  faSprayCanSparkles,
  faWandMagicSparkles,
  faHandSparkles,
  faSpa,
  faHeart,
  faPlay,
  faImages,
  faCircleCheck,
  faCircleExclamation,
  faUserTie,
  faPalette,
  faWind,
  faBrush,
  faLeaf,
  faQuoteLeft,
  faMapLocationDot,
  faDirections,
  faCheck,
  faBroom,
  faUsers,
  faMugHot,
  faVolumeHigh,
  faVolumeXmark,
} from '@fortawesome/free-solid-svg-icons'
import {
  faInstagram,
  faFacebook,
  faWhatsapp,
  faTiktok,
} from '@fortawesome/free-brands-svg-icons'

library.add(
  faScissors,
  faStar,
  faStarHalfStroke,
  faLocationDot,
  faClock,
  faPhone,
  faEnvelope,
  faCalendarCheck,
  faArrowRight,
  faArrowLeft,
  faChevronDown,
  faBars,
  faTableCellsLarge,
  faXmark,
  faSun,
  faMoon,
  faSprayCanSparkles,
  faWandMagicSparkles,
  faHandSparkles,
  faSpa,
  faHeart,
  faPlay,
  faImages,
  faCircleCheck,
  faCircleExclamation,
  faUserTie,
  faPalette,
  faWind,
  faBrush,
  faLeaf,
  faQuoteLeft,
  faMapLocationDot,
  faDirections,
  faCheck,
  faBroom,
  faUsers,
  faMugHot,
  faVolumeHigh,
  faVolumeXmark,
  faInstagram,
  faFacebook,
  faWhatsapp,
  faTiktok,
)

export { FontAwesomeIcon }
